version: '3'

services:
  tensorflow-serving:
     image: tensorflow/serving
     ports: 
        - "8501:8501"
     volumes:
        - ./server/leaves_classifier:/models/leaves_classifier
     environment:
        - MODEL_NAME=leaves_classifier 
  flask_api:
     container_name: flask_api
     image: 26031959/tomato-api
     ports:
        - "80:5000"
     depends_on:
        - tensorflow-serving
     volumes:
        - ./server/app.py:/app.py
        - ./server/diseases.json:/diseases.json 
