version: '3'

services:
  tensorflow-serving:
     image: tensorflow/serving
     ports: 
        - "8501:8501"
     volumes:
        - ./leaves_classifier:/models/leaves_classifier
     environment:
        - MODEL_NAME=leaves_classifier 
  flask_api:
     container_name: flask_api
     image: tomato-api
     ports:
        - "5000:5000"
     depends_on:
        - tensorflow-serving
     build:
        context: .
        dockerfile: Dockerfile 
     volumes:
        - ./leaves.py
        - ./diseases.json 

